#!/usr/bin/python
#

import sys, string
from socket import *

if len(sys.argv)<3:
   print 'ERROR: Format %s port and file'%sys.argv[0]
else:
   port=int(sys.argv[1])
   sock=socket(AF_INET,SOCK_DGRAM)
   sock.bind(('',int(port)))
   data='None'
   open(sys.argv[2],'w').write( sock.recvfrom(1024000000)[0])

